In [1]:
import pandas as pd

In [3]:
origen = 'enviados-const_merged_0-2025-08-29T09-23.csv'
df = pd.read_csv(origen)
df.head()

,nombre,dir,tlf,enviado
0,Vidrios Millicay (vidriería y aberturas de alu...,1546 Félix Paz,3514666826,False
1,Metalurgica Tobías,2626 Avenida Monseñor Pablo Cabrera,3516770759,True
2,La Banderola® – Aberturas,·,3516347939,True
3,Vidrios y Aberturas don Bosco,Av. Don Bosco 5011,3515575052,True
4,Alce Aberturas,Av. Colón 3879,3513936028,True

In [10]:
sin_wp = df[df['enviado'] == False]
con_wp = df[df['enviado'] == True]

In [32]:
print(sin_wp.shape, con_wp.shape)

(42, 4) (43, 4)

In [27]:
df[(df['tlf'] == 3516770759)]

,nombre,dir,tlf,enviado
1,Metalurgica Tobías,2626 Avenida Monseñor Pablo Cabrera,3516770759,True