In [125]:
import pandas as pd
import numpy as np
import re

In [126]:
ruta_base = './archivos/'
sub = 'excels/'
archivo = 'db2.xlsx'
final = ruta_base+sub+archivo
# print(final)
df = pd.read_excel(final)
df.columns = [name.lower() for name in df.columns]
df.head(2)

,cliente,edad,prepago,desregulado,grupo familiar,opcion de cambio,telefono,plan cotizado,estado,unnamed: 9,unnamed: 10,unnamed: 11
0,FACUNDO FERREYRA,NaN,NaN,NaN,NaN,NaN,3.513678e+09,NaN,RECHAZA INFO,NaN,NaN,NaN
1,ELIANA GHELLI,44-44-15-3,PREPAGO,NaN,4.0,PREPAGO,3.515164e+09,NaN,NaN,NaN,NaN,NaN

In [127]:
# arreglar numero de telefono
def es_telefono (num):
    if pd.isna(num) or not isinstance(num, (str, int, float)):
        return None
    if isinstance(num, float): # Convert float to integer first to remove decimals, then to string
        num = int(num)
    tlf = re.sub(r'\D', '', str(num))
    if len(tlf) in [10, 12, 14]:
        return tlf
    return None

def buscar_telefono(fila):
    for valor in fila:
        valor = es_telefono(valor)
        if valor:
            return valor

In [128]:
df['tlf'] = df.apply(buscar_telefono, axis=1)
df = df.loc[:, ["cliente", "edad", "tlf"]]
df['cliente'] = df['cliente'].str.title()
df.columns = ['nombre', 'edades', 'tlf']
filtro_sin_tlf = df['tlf'].notna()
df = df[filtro_sin_tlf]

In [129]:
df.to_csv('db2.csv', index=False)

In [130]:
df

                        nombre        edades         tlf
0            Facundo Ferreyra            NaN  3513678235
1                Eliana Ghelli    44-44-15-3  3515163560
2               Tamara Belloni           -45  3517692128
3                 Marcos Lupo             45  3517595049
6           Facundo Altamirano            22  3512267212
8                Dilan Zalazar            19  3516561520
9                 Camila Mensi            22  2954222316
10              Noelia Carrizo           -30  3512056770
11                 Enzo Sallas           -30  3513980257
12              Agustin Oviedo            20  3518566550
13      Araceli Anahi Aliendro           NaN  3513569391
14          Melani Supichiatti            20  3512198089
15          Florencia Gordillo           -30  3535623327
16       Maria Eugenia Cortiña           -30  3517054916
17  Diego Sebastian Mendizabal           NaN  3535623327
18             Silvina Caceres           NaN  3517054916
19              Melina Rocuzzo           NaN  3516269586
20            Guillermo Llanos           NaN  3513821603
22             Carla Eleonora            NaN  3517536450
24             Brenda Peralta            NaN  3547500592
25               Benilda Juipa            37  3516658559
26          Victoria Ugliarolo           NaN  3515329664
27              Analia Freytes           NaN  3546400658
28           Gabriel Possidoni            39  3512550400
29         Eleonora Martellosi           NaN  3525555411
30               Laura Heumann           NaN  3513842552
31              Diana Pastroyo            40  3517016180
32               Cesar Matias     37 2 HIJOS  3513569191
33               Leonel Guzman       20 AÑOS  3517058871
34               Alejo Callana      21 AÑOS   3513027278
35              Joaquin Suarez       29 AÑOS  3515153228
36              Nicolas Chavez  26-23-4 AÑOS  3516143924
37           Leonardo Sequeira      32-32-13  3512582830
38              Matias Ledesma     28-28-7-2  3513590874
39               Elias Moreira       32 AÑOS  3517077590
40             Michell Pereira           NaN  3516200935
41               Agustin Arias       23 AÑOS  3518640828
42            Peralta Gonzalo       27 AÑOS   3516972761
43           Geremias Giuipomi      20 AÑOS   3515131772
44             Micael Viarengo      29 AÑOS   3512037291
45             Fabricio Flores      35 AÑOS   3517354792
46              Damian Sutera             48  3516809569
47              Rodrigo Copola      23 AÑOS   3512506647
48        Maximiliano Depetris      32 AÑOS   3513204869