In [1]:
import pandas as pd
import os
import re

In [2]:
# 1. Configuración inicial
query = 'const'
input_folder = f'./archivos/busquedas/{query}/mod/'  # Cambia esto
target_file = f'{query}_merged.csv'
destination = input_folder+target_file
# columnas_relevantes = ['nombre', 'dir', 'tlf']  # Ajusta con tus nombres reales

In [3]:

def solo_digitos(tlf):
   return re.sub(r'\D', '', str(tlf))

# 2. Procesar todos los archivos CSV
dfs = []
for filename in os.listdir(input_folder):
    if filename.endswith('.csv'):
        filepath = os.path.join(input_folder, filename)
        if 'mod_' in filepath:
            df = pd.read_csv(filepath)
            dfs.append(df)

dfs

[                                                nombre  \
 0    Vidrios Millicay (vidriería y aberturas de alu...
 1                                   Metalurgica Tobías
 2                Grupo Shutó -Aberturas de PVC - REHAU
 3                            La Banderola® – Aberturas
 4                        Vidrios y Aberturas don Bosco
 ..                                                 ...
 111                                    Selec Aberturas
 112                     Chávez Aberturas-Amoblamientos
 113                                        Inmecar SRL
 114                                    Noval Aberturas
 115  ALU.COM Fabrica de Aberturas y Amoblamientos -...

                                                 dir           tlf
 0                                    1546 Félix Paz    3514666826
 1               2626 Avenida Monseñor Pablo Cabrera    3516770759
 2                                                 ·    3516191821
 3                                                 ·    3516347939
 4                                Av. Don Bosco 5011    3515575052
 ..                                              ...           ...
 111                         MITRE, Las Varillas 695  353315431640
 112  Santa Clara De Asis, Dr. Arturo Capdevila 2264    3514780718
 113                                               ·    3514994510
 114                                               ·    3513407744
 115                                E. Bodereau 9576  351157565756

 [116 rows x 3 columns],
                                                 nombre  \
 0                              Estudio de Arquitectura
 1                         Lorena Busquets Arquitectura
 2              Boris Haedo Arquitectura y Construcción
 3                                     RMN Arquitectura
 4        Palmero Vucovich - Arquitectura + desarrollos
 ..                                                 ...
 108  Grandio. Hüga. Arquitectura. Ingeniería. Premo...
 109             Estudio de Arquitectura y Construcción
 110                      Estudio de Arquitectura TAARQ
 111          Mubarqui estudio de Arquitectura y diseño
 112                          Arquitectura Construccion

                                                  dir         tlf
 0                              1537 José Roque Funes  3515914092
 1                                1250 Bv Elias Yofre  3513123365
 2                                          Buceo 314  3513482546
 3                                    9 de Julio 3386  3513194008
 4               Luis Jose de Tejeda 4212 Planta Baja  3514817388
 ..                                               ...         ...
 108                          José Manuel Estrada 265  3514698259
 109  Quintas de Argüello, José Wenceslao Agusti 7672  3543447535
 110                                              NaN  3515184150
 111                               Pje. Alicante 2432  3513856802
 112                                      Cannes 3543  3514617550

 [113 rows x 3 columns],
                                           nombre  \
 0                 Pronta Viviendas Prefabricadas
 1                   Lorena Busquets Arquitectura
 2                  Construcciones - Oscar Quispe
 3                         Item Construcciones Sa
 4                   TECTURA Construcción en seco
 ..                                           ...
 110                    Setien Construcciones SRL
 111                           L&L Construcciones
 112                        ORODAZ CONSTRUCCIONES
 113                         Comar Construcciones
 114  MP Estudio de Arquitectura y Construcciones

                                dir           tlf
 0           3031 De los Calabreses    3512378166
 1              1250 Bv Elias Yofre    3513123365
 2                     Caseros 4300  351156589216
 3             Dr. Pedro Chutro 952    3514804844
 4                                ·    3514815939
 ..                             ...           ...
 110         Dr. Carlos Chagas 5641    3543421371
 111                Cruz Chica 4950    3521400398
 112                              ·    3514931043
 113  Av. Italia 900 lote 6 manz 72    3515514729
 114                              ·  351153417322

 [115 rows x 3 columns],
                               nombre  \
 0                    Sol de Mayo SRL
 1             TCM Hornos para Madera
 2                      Maderas Colon
 3                     Maderas Nahuel
 4                M S - Maderas Sucre
 ..                               ...
 118                  La Obra Maderas
 119  Claudio Pereyra Pisos De Madera
 120                      Duomo store
 121                 Muebles de Campo
 122                Garin Pinturerias

                                           dir           tlf
 0                             573 Sol de Mayo    3516331997
 1                         2168 Justo Arguello    3513028348
 2                                           ·  351157580490
 3                                           ·    3514898108
 4                    Docentes Argentinos 6541    3517158706
 ..                                        ...           ...
 118                       Río de Janeiro 1495    3516199250
 119                          Guillermo Hudson    3512466897
 120                       Emilio Lamarca 4192    3514812512
 121  Gral. Manuel Belgrano, Barrio Güemes 704    3512810808
 122                                Sta Fe 418    3512728629

 [123 rows x 3 columns]]

In [4]:

# 3. Consolidación y eliminación de duplicados
if dfs:
    # print('ok')
    consolidated = pd.concat(dfs, ignore_index=True)

    # consolidated = consolidated.iloc[:, :-2]
    # consolidated.iloc[:,2] = consolidated.iloc[:,2].str.replace(r'\D+', '', regex=True)

        # Verificación antes de eliminar duplicados
    print(f"\nRegistros totales antes de eliminar duplicados: {len(consolidated)}")
    print(f"Duplicados detectados: {consolidated.duplicated().sum()}")
    # Eliminar duplicados considerando todas las columnas
    consolidated = consolidated.drop_duplicates()
    print(f"Registros totales: {len(consolidated)}")
    
    # Opcional: eliminar duplicados basados en columnas clave
    # consolidated = consolidated.drop_duplicates(subset=['col1', 'col2'])
    
    # # Guardar resultado
    consolidated.to_csv(destination, index=False)
    print(f"Archivo consolidado guardado como {destination}")
else:
    print("No se encontraron archivos CSV en la carpeta")

consolidated.head()

Registros totales antes de eliminar duplicados: 467
Duplicados detectados: 27
Registros totales: 440
Archivo consolidado guardado como ./archivos/busquedas/const/mod/const_merged.csv

,nombre,dir,tlf
0,Vidrios Millicay (vidriería y aberturas de alu...,1546 Félix Paz,3514666826
1,Metalurgica Tobías,2626 Avenida Monseñor Pablo Cabrera,3516770759
2,Grupo Shutó -Aberturas de PVC - REHAU,·,3516191821
3,La Banderola® – Aberturas,·,3516347939
4,Vidrios y Aberturas don Bosco,Av. Don Bosco 5011,3515575052

In [5]:
merged = pd.read_csv(destination)
merged.head(20)

,nombre,dir,tlf
0,Vidrios Millicay (vidriería y aberturas de alu...,1546 Félix Paz,3514666826
1,Metalurgica Tobías,2626 Avenida Monseñor Pablo Cabrera,3516770759
2,Grupo Shutó -Aberturas de PVC - REHAU,·,3516191821
3,La Banderola® – Aberturas,·,3516347939
4,Vidrios y Aberturas don Bosco,Av. Don Bosco 5011,3515575052
5,Alce Aberturas,Av. Colón 3879,3513936028
6,Aberturas Alemanas,Av. Colón 5525,3514854000
7,PMA ALUMINIOS,Humahuaca 405,3512162226
8,servicio de abertura,José Barros Pazos 3175,3512067500
9,Aberturas Serafini,Domingo Zípoli 242,3516363654
10,Aluminio Color,Av. Duarte Quirós 3930,3514897575
11,SODIMAC® [Tienda: Córdoba],·,8102227634
12,Aberturas Pizarro,Gral. Alvear 701,351155942420
13,"Sur Aberturas de Aluminio, Cortinas de enrollar",27 de Abril 2882,3513880043
14,Aberturas de Madera,Domingo Zípoli 258,3516363654
15,Aluhaus Aberturas de Aluminio,·,3514660384
16,Franco Aberturas,·,3515521603
17,Metro Aluminio S.a.,Baudilio Vazquez 3730,3512501110
18,Aberturas Almondo,"AV. Fuerza Aérea 4600, Av. Fuerza Aérea Argent...",351158173588
19,Cerramientos Meyer,"Argentina N°3333, Av. Fuerza Aérea Argentina",3514663569