In [14]:
import pandas as pd
import os
import re

In [15]:
# 1. Configuración inicial
query = 'servicios'
input_folder = f'./archivos/busquedas/{query}/'  # Cambia esto
output_folder = './archivos/'
target_file = f'{query}_merged.csv'
destination = output_folder+target_file
# columnas_relevantes = ['nombre', 'dir', 'tlf']  # Ajusta con tus nombres reales

In [19]:

def solo_digitos(tlf):
   return re.sub(r'\D', '', str(tlf))

# 2. Procesar todos los archivos CSV
dfs = []
for filename in os.listdir(input_folder):
    if filename.endswith('.csv'):
        filepath = os.path.join(input_folder, filename)
        if 'mod_' in filepath:
            df = pd.read_csv(filepath)
            dfs.append(df)

dfs

[                                               nombre  \
 0   Sergio Blanco Reparación de máquinas de coser ...
 1                                       Suiza Técnico
 2   Grupo Service Córdoba - Lavarropas, Lavavajill...
 3                                               G.D.V
 4                      Servicio Técnico de Lavarropas
 5                     RG REFRIGERACIÓN RICARDO GARCÍA
 6                                     Sei electrónica
 7                      Kabichian Servicio Multimarcas
 8                                       Sport Service
 9                      El Emporio de las Reparaciones
 10                             Taller Castaño Service
 11                                            Lubimax
 12  MR Heladeras. Reparacion de Heladeras. Lavarro...
 13                                     Servicios Urca
 14                                    Service Benelli
 15                                 Lubricentro Matute
 16                           Maipú Chevrolet Servicio
 17  Sergio Blanco Reparación de máquinas de coser ...
 18                                        A&A Service
 19            Service de máquinas de coser Pedro Cruz
 20                          LAZO LUCION REFRIGERACION
 21                   Bosch Car Service - Bittor Ariel
 22                                      Suiza Técnico
 23                                   FYAZ Electrónica
 24        Reparacion Electrodomésticos. Docta Service
 25                                 Audi Service Maipu
 26                          Maipú Volkswagen Servicio
 27                                   Esquimal Service
 28                              Integral Cars Service
 29      Mundo Maipú – Centro de repuestos y servicios
 30                                     Service Valejo
 31                     Service de Heladera en Cordoba
 32                                        TODOSERVICE
 33                                            Lubimax
 34  ECO AUTO, SERVICIO INTEGRAL DEL AUTOMOTOR! AIR...
 35  TITAN EL DOCTOR DEL AIRE ACONDICIONADO y MANTE...
 36                                   Cold Service CBA
 37                                   FYAZ Electrónica
 38  Multiservicio electrónico Otiniano servicio te...
 39                                 Lubricentro Wallas
 40                                     Center service
 41                                   JV Refrigeración
 42                                   Servicio Técnico
 43                        Marcos ocampo refrigeracion
 44                       Electrónica Santa Fe Service
 45                                   Tecno @ Services
 46                                   Celi Car Service
 47                                J&M Taller Integral
 48                      Servicio Técnico Oficial line
 49                                     Yuhmak Service
 50                                Maipú Ford Servicio
 51                                         Drudi Naum
 52                                      Honda Service
 53               Service Oficial Center Nueva Córdoba
 54                                 Electrónica Visión

                                                   dir           tlf
 0                                   527 Maestro Vidal    3517870676
 1                                     1046 Deán Funes    3513521298
 2                             Juan García Martínez 65    3517061881
 3     Angelo de Peredo 3598, Platanos, Félix Paz 1100    3518065965
 4                                     9 de Julio 4380    3512038163
 5                                  Duarte Quirós 4430    3515308104
 6                                   Maestro Vidal 308    3512672241
 7                                                   ·    3515212773
 8                                                   ·  351153020057
 9                                    27 de Abril 3000  354115618780
 10                                                  ·    3513224443
 11                                                  ·    3515639559
 12                                      Esperanto 556    3513615784
 13               Luis García Lagos 1188 Local 5, Urca    3515113041
 14                            Ángel Fausto Ávalos 720    3516511743
 15                                      Félix Paz 908    3514885058
 16                                                  ·    3514859560
 17                                                  ·    3517870676
 18                            Aviador Richardson 2114    3515444786
 19                              Luis de Azpeitía 2902    3514218307
 20                                          Vélez 545    3516123350
 21                                                  ·    3513250411
 22                                    1046 Deán Funes    3513521298
 23  Av. Santa Ana 3934 Galería Comercial Palmera L...    3514884414
 24                             Raúl Hugo Espoile 2962    3518611756
 25                                                  ·    3514859575
 26                                                  ·    3514859587
 27                                          Nazca 651    3516283659
 28                                                  ·    3516784404
 29                                                  ·    3514859610
 30                        X5011BVB, Luis Pasteur 1976    3515950330
 31                                     Sipe Sipe 1120    3515182774
 32                                                  ·  351152637218
 33                                                  ·    3515639559
 34                                                  ·    3516195607
 35                                     Juan Piñero 10    3513101427
 36                   X5003APO, Dr. Andrés Llobet 2700  351153065508
 37  Av. Santa Ana 3934 Galería Comercial Palmera L...  351153309681
 38                                                  ·    3515149918
 39                                                  ·    3513243289
 40                    Barrio avenida, Luis Agote 2172    3515743227
 41                               Quebracho Herrado 11    3513413411
 42                                 Maestro Vidal 1616    3516516262
 43                                      Sta Rosa 5443    3517534620
 44                                Alberdi, Sta Fe 108    3514270317
 45                     Av. Emilio Caraffa 2888 Loc. 1  351153111707
 46                                                  ·    3519061400
 47                                                  ·    3515468882
 48                               Caseros 1091 Local 2    3515747580
 49                                     Av. Colón 4450  351158094086
 50                                                  ·    3514859500
 51                             Av. Duarte Quirós 4830    3516132231
 52                                    Deán Funes 3385    3516181529
 53            Independencia. 5014 Córdoba AR, C.P 467    3512388049
 54               Dr, Observatorio, Mariano Moreno 861    3515046345  ,
                                                nombre                  dir  \
 0                                   UM Multiservicios   3424 Duarte Quirós
 1                      Kabichian Servicio Multimarcas                    ·
 2   Estación de Servicios YPF - Grupo Manzi- Colón...       Av. Colón 4272
 3                                SM servicio mecanico        Félix Paz 720
 4                           At neumaticos y servicios   Duarte Quirós 3664
 ..                                                ...                  ...
 86  Sempreco Servicios de Limpieza y Mantenimiento...                    ·
 87                      Kazaró - Servicio de Limpieza                    ·
 88                                               Igui                    ·
 89  Servicio Bronstein SRL - Servicio oficial Hyun...                    ·
 90                                  Servicios Guevara  Colonia Achira 4050

            tlf
 0   3518188093
 1   3515212773
 2   3514844446
 3   3513910474
 4   3516665312
 ..         ...
 86  3517940036
 87  3518197771
 88  3541521868
 89  3516330300
 90  3515132862

 [91 rows x 3 columns]]

In [24]:

# 3. Consolidación y eliminación de duplicados
if dfs:
    # print('ok')
    consolidated = pd.concat(dfs, ignore_index=True)

    # consolidated = consolidated.iloc[:, :-2]
    # consolidated.iloc[:,2] = consolidated.iloc[:,2].str.replace(r'\D+', '', regex=True)

        # Verificación antes de eliminar duplicados
    print(f"\nRegistros totales antes de eliminar duplicados: {len(consolidated)}")
    print(f"Duplicados detectados: {consolidated.duplicated().sum()}")
    # Eliminar duplicados considerando todas las columnas
    consolidated = consolidated.drop_duplicates()
    print(f"Registros totales: {len(consolidated)}")
    
    # Opcional: eliminar duplicados basados en columnas clave
    # consolidated = consolidated.drop_duplicates(subset=['col1', 'col2'])
    
    # # Guardar resultado
    consolidated.to_csv(destination, index=False)
    print(f"Archivo consolidado guardado como {destination}")
else:
    print("No se encontraron archivos CSV en la carpeta")

consolidated.head()

Registros totales antes de eliminar duplicados: 146
Duplicados detectados: 15
Registros totales: 131
Archivo consolidado guardado como ./archivos/servicios_merged.csv

,nombre,dir,tlf
0,Sergio Blanco Reparación de máquinas de coser ...,527 Maestro Vidal,3517870676
1,Suiza Técnico,1046 Deán Funes,3513521298
2,"Grupo Service Córdoba - Lavarropas, Lavavajill...",Juan García Martínez 65,3517061881
3,G.D.V,"Angelo de Peredo 3598, Platanos, Félix Paz 1100",3518065965
4,Servicio Técnico de Lavarropas,9 de Julio 4380,3512038163

In [ ]:
merged = pd.read_csv(destination)
merged.head(20)

,nombre,dir,tlf
0,Sergio Blanco Reparación de máquinas de coser ...,527 Maestro Vidal,3517870676
1,Suiza Técnico,1046 Deán Funes,3513521298
2,"Grupo Service Córdoba - Lavarropas, Lavavajill...",Juan García Martínez 65,3517061881
3,G.D.V,"Angelo de Peredo 3598, Platanos, Félix Paz 1100",3518065965
4,Servicio Técnico de Lavarropas,9 de Julio 4380,3512038163
5,RG REFRIGERACIÓN RICARDO GARCÍA,Duarte Quirós 4430,3515308104
6,Sei electrónica,Maestro Vidal 308,3512672241
7,Kabichian Servicio Multimarcas,·,3515212773
8,Sport Service,·,351153020057
9,El Emporio de las Reparaciones,27 de Abril 3000,354115618780
10,Taller Castaño Service,·,3513224443
11,Lubimax,·,3515639559
12,MR Heladeras. Reparacion de Heladeras. Lavarro...,Esperanto 556,3513615784
13,Servicios Urca,"Luis García Lagos 1188 Local 5, Urca",3515113041
14,Service Benelli,Ángel Fausto Ávalos 720,3516511743
15,Lubricentro Matute,Félix Paz 908,3514885058
16,Maipú Chevrolet Servicio,·,3514859560
17,Sergio Blanco Reparación de máquinas de coser ...,·,3517870676
18,A&A Service,Aviador Richardson 2114,3515444786
19,Service de máquinas de coser Pedro Cruz,Luis de Azpeitía 2902,3514218307

: